export const LOAD_ACCOUNTS = "LOAD_ACCOUNTS";
export const DEPLOYED_CAMPAIGNS = "DEPLOYED_CAMPAIGNS";
export const GET_CAMPAIGN_DETAILS = "GET_CAMPAIGN_DETAILS";
export const GET_REQUESTS = "GET_REQUESTS";